"""Alembic's environment: where the migrations run (DR-14).

The application store only. The warehouse is never migrated: Cartograph
reads it through a role that cannot write (NFR-07), and this file never
sees its URL.

The URL comes from APP_DATABASE_URL in the environment, or, for a test
that migrates a scratch database, from the `sqlalchemy.url` option set on
the Config it was given. It is never read from a tracked file and never
logged: the URL holds the password (NFR-09).

Migrations are written as explicit SQL. There are no ORM models to
compare against, so nothing is autogenerated.
"""

import os

from alembic import context
from sqlalchemy import create_engine, pool

config = context.config


def _url() -> str:
    url = config.get_main_option("sqlalchemy.url") or os.environ.get("APP_DATABASE_URL")
    if not url:
        raise RuntimeError("APP_DATABASE_URL is not set: there is no application database to migrate")
    # The application's URLs name no driver; SQLAlchemy must be told to use
    # psycopg 3, the one that is installed.
    for scheme in ("postgresql://", "postgres://"):
        if url.startswith(scheme):
            return "postgresql+psycopg://" + url[len(scheme) :]
    return url


def run_migrations() -> None:
    if context.is_offline_mode():
        raise RuntimeError("offline mode would print the SQL without running it; it is not supported here")
    engine = create_engine(_url(), poolclass=pool.NullPool)
    with engine.connect() as connection:
        context.configure(connection=connection, target_metadata=None)
        with context.begin_transaction():
            context.run_migrations()
    engine.dispose()


run_migrations()
