"""tpcds_ri.sql -> foreign keys -> the overlay's relationships section.

The foreign keys of the TPC-DS warehouse are never written by hand (Charter
D-10). They are read from the toolkit's published constraint file, and
everything else -- the overlay, the primary keys, the expected edge count --
is derived from that one reading.

The file itself is the TPC's and is not committed. scripts/warehouse.sh
fetches it beside this module from the URL below and refuses any content
whose sha256 is not the one pinned here. The overlay generated from it is
committed, so the edge list does not depend on the mirror staying up.

Pure and standard-library only (DD-01): text in, values out. The warehouse
build runs it on the host before any container is involved, and the tests
run it with no database.

The parser is strict on purpose. A line it cannot classify raises; it is
never skipped. A dropped statement would be a missing edge, and a missing
edge is silent everywhere downstream (T-01).
"""

import hashlib
import re
import sys
from dataclasses import dataclass
from pathlib import Path

RI_FILE = Path(__file__).with_name("tpcds_ri.sql")

# A public mirror of the TPC-DS toolkit, pinned to a commit rather than a
# branch, and to a hash rather than to trust. If either changes, that is a
# decision, and it is made here and in the test's expected edge count -- not
# by accident.
RI_URL = (
    "https://raw.githubusercontent.com/gregrahn/tpcds-kit/"
    "5a3a81796992b725c2a8b216767e142609966752/tools/tpcds_ri.sql"
)
RI_SHA256 = "c5fc873d832c6bf5362cb8bd89d6131c65cdb50712301e9f08ccf92213f92d5b"

# One statement, whole line, single-column key on both sides. Anchored at
# both ends: a composite key or a trailing clause fails to match and raises
# rather than being half-read.
_STATEMENT = re.compile(
    r"""alter \s+ table \s+ (?P<from_table>\w+) \s+
        add \s+ constraint \s+ (?P<name>\w+) \s+
        foreign \s+ key \s* \( \s* (?P<from_column>\w+) \s* \) \s*
        references \s+ (?P<to_table>\w+) \s* \( \s* (?P<to_column>\w+) \s* \) \s* ;""",
    re.IGNORECASE | re.VERBOSE,
)


@dataclass(frozen=True)
class ForeignKey:
    name: str
    from_table: str
    from_column: str
    to_table: str
    to_column: str


def parse(text: str) -> list[ForeignKey]:
    """Every active statement in the file, in file order.

    Blank lines and `--` comments are the only things passed over. That
    includes the statements the TPC authors themselves commented out: they
    name columns that do not exist in the schema, and are not relationships.
    """
    keys: list[ForeignKey] = []
    for number, raw in enumerate(text.splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("--"):
            continue
        match = _STATEMENT.fullmatch(line)
        if match is None:
            raise ValueError(f"tpcds_ri.sql line {number}: not a foreign key statement: {line!r}")
        keys.append(ForeignKey(**{k: v.lower() for k, v in match.groupdict().items()}))

    _reject_duplicates(keys)
    return keys


def _reject_duplicates(keys: list[ForeignKey]) -> None:
    names = [key.name for key in keys]
    columns = [(key.from_table, key.from_column) for key in keys]
    for label, values in (("constraint name", names), ("referencing column", columns)):
        repeated = sorted({v for v in values if values.count(v) > 1})
        if repeated:
            raise ValueError(f"tpcds_ri.sql: repeated {label}: {repeated}")


def primary_keys(keys: list[ForeignKey]) -> dict[str, str]:
    """Table -> the column that must be unique for the foreign keys to apply.

    Derived, not listed: a foreign key needs a unique target, so the set of
    referenced columns *is* the set of primary keys the load has to add.
    """
    targets: dict[str, str] = {}
    for key in keys:
        known = targets.setdefault(key.to_table, key.to_column)
        if known != key.to_column:
            raise ValueError(f"{key.to_table} is referenced by two different columns: {known}, {key.to_column}")
    return dict(sorted(targets.items()))


def render_overlay(keys: list[ForeignKey]) -> str:
    """The overlay file (DD-16), relationships section only.

    Written by hand rather than through a YAML library so the host needs
    nothing installed; every value is a bare identifier, so there is nothing
    to quote. The test reads it back with a real YAML parser.
    """
    lines = [
        "# Cartograph overlay for the TPC-DS warehouse (DD-16).",
        "#",
        "# GENERATED by scripts/warehouse.sh from backend/warehouse/tpcds_ri.sql.",
        "# Do not edit: regenerate. The source file's sha256 is",
        f"# {RI_SHA256}",
        "#",
        f"# {len(keys)} foreign keys the generated warehouse does not declare (FR-43).",
        "# The naming and preferences sections arrive at build step 3.",
        "",
        "relationships:",
    ]
    for key in keys:
        lines.append(f"  - from: {key.from_table}.{key.from_column}")
        lines.append(f"    to:   {key.to_table}.{key.to_column}")
    return "\n".join(lines) + "\n"


def render_primary_keys(keys: list[ForeignKey]) -> str:
    return "".join(
        f"alter table {table} add primary key ({column});\n" for table, column in primary_keys(keys).items()
    )


def load() -> list[ForeignKey]:
    raw = RI_FILE.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != RI_SHA256:
        raise ValueError(f"{RI_FILE.name} has changed: sha256 {digest}, expected {RI_SHA256}")
    return parse(raw.decode("ascii"))


if __name__ == "__main__":
    # `source` prints where the file comes from and what it must hash to, and
    # is the one command that works before the file exists.
    renderers = {"overlay": render_overlay, "primary-keys": render_primary_keys}
    command = sys.argv[1] if len(sys.argv) == 2 else None
    if command == "source":
        print(RI_URL, RI_SHA256)
    elif command in renderers:
        sys.stdout.write(renderers[command](load()))
    else:
        sys.exit(f"usage: ri.py {{source|{'|'.join(renderers)}}}")
