"""SemanticIndex: the schema's descriptions as vectors and as searchable
text, and every element scored against a piece of text (FR-06, FR-07,
DR-11, DD-08, DD-09).

Impure, and so in shell/ (DD-01): it holds the application database and an
Embedder. It decides nothing. It returns raw numbers -- a cosine similarity
and a text-search rank for every element -- and the Retriever, in the core,
does everything that is a decision.

EMBEDDED ONCE PER SNAPSHOT (DR-11). `embed_schema` embeds the elements of
a snapshot that have no vector yet and records the model on the snapshot.
Run again, it finds nothing to do and calls nobody. A snapshot embedded by
one model is never topped up by another: that would put vectors from two
spaces in one column, and every similarity across them would be noise that
looks like a number.

TWO SEARCHES OVER ONE TEXT (DD-09). Each element has one `search_text`. Its
vector is that text embedded; its `fts` is that text as a tsvector,
generated by Postgres. So the semantic and the literal score of an element
are always about the same words.

  semantic   1 - cosine distance, by pgvector, over every row. Exact: there
             is no approximate index.
  keyword    ts_rank against the text's words joined by OR. Postgres's
             plainto_tsquery joins them by AND, which asks that one
             description hold every word of the question; none ever would.
             A text with no words left after stopwords matches nothing and
             every element scores 0.

WORDS (ruling h). `tokens` splits a text with Postgres's own `english`
configuration, so the stopword list is the one PostgreSQL ships, read
through the database and copied nowhere, and the words the keyword search
ignores are exactly the words the term list ignores.
"""

from dataclasses import dataclass

import psycopg

from app.core.retriever import RawScore, Term, Token, make_terms
from app.shell.embedder import Embedder

# ts_debug's names for a hyphenated compound as a whole. Its parts follow
# as tokens of their own, so the whole is skipped.
_COMPOUNDS = {"asciihword", "hword", "numhword"}

_SCORE = """
    select e.table_name, e.column_name,
           1 - (e.embedding <=> %(vector)s::vector),
           ts_rank(e.fts, q.query)
    from schema_elements e,
         (select replace(plainto_tsquery('english', %(text)s)::text, '&', '|')::tsquery as query) q
    where e.snapshot_id = %(snapshot)s
    order by e.position
"""


class SchemaNotEmbedded(RuntimeError):
    """The current snapshot has elements with no vector."""


class EmbeddingModelMismatch(RuntimeError):
    """The snapshot was embedded by a different model than the one offered."""


@dataclass(frozen=True)
class EmbedReport:
    snapshot_id: int
    model: str
    # Elements embedded by this call, and how many already had a vector.
    embedded: int
    already: int
    tokens: int
    cost_usd: float


@dataclass(frozen=True)
class ScoredQuestion:
    question: str
    scores: tuple[RawScore, ...]
    # Each term of the question with every element scored against it alone.
    terms: tuple[tuple[Term, tuple[RawScore, ...]], ...]


class SemanticIndex:
    def __init__(self, dsn: str, embedder: Embedder) -> None:
        self._dsn = dsn
        self._embedder = embedder

    def embed_schema(self, snapshot_id: int) -> EmbedReport:
        with psycopg.connect(self._dsn) as connection:
            (model,) = connection.execute(
                "select embedding_model from schema_snapshots where id = %s", (snapshot_id,)
            ).fetchone()
            if model is not None and model != self._embedder.model:
                raise EmbeddingModelMismatch(
                    f"snapshot {snapshot_id} was embedded with {model}; refusing to add vectors from "
                    f"{self._embedder.model} beside them"
                )
            (total,) = connection.execute(
                "select count(*) from schema_elements where snapshot_id = %s", (snapshot_id,)
            ).fetchone()
            missing = connection.execute(
                "select id, search_text from schema_elements where snapshot_id = %s and embedding is null "
                "order by position",
                (snapshot_id,),
            ).fetchall()
            if not missing:
                return EmbedReport(snapshot_id, self._embedder.model, 0, total, 0, 0.0)

            result = self._embedder.embed([text for _, text in missing])
            with connection.cursor() as cursor:
                cursor.executemany(
                    "update schema_elements set embedding = %s::vector where id = %s",
                    [(_literal(vector), element) for (element, _), vector in zip(missing, result.vectors)],
                )
            connection.execute(
                "update schema_snapshots set embedding_model = %s where id = %s", (self._embedder.model, snapshot_id)
            )
        return EmbedReport(
            snapshot_id, self._embedder.model, len(missing), total - len(missing), result.tokens, result.cost_usd
        )

    def tokens(self, text: str) -> tuple[Token, ...]:
        """The text's words in order, each marked content or not. A
        stopword and a punctuation mark are both not content, and both keep
        two words from being adjacent. Spaces and hyphens are dropped."""
        with psycopg.connect(self._dsn) as connection:
            rows = connection.execute("select alias, token, lexemes from ts_debug('english', %s)", (text,)).fetchall()
        tokens = []
        for alias, token, lexemes in rows:
            if alias in _COMPOUNDS:
                continue
            if alias == "blank":
                if token.strip(" \t\r\n-"):
                    tokens.append(Token(token.strip(), False))
                continue
            tokens.append(Token(token, bool(lexemes)))
        return tuple(tokens)

    def score(self, text: str) -> tuple[RawScore, ...]:
        """Every element of the current snapshot against one text."""
        return self.score_many([text])[0]

    def score_many(self, texts: list[str]) -> list[tuple[RawScore, ...]]:
        """As `score`, for several texts with one call to the embedder."""
        if not texts:
            return []
        vectors = self._embedder.embed(texts).vectors
        with psycopg.connect(self._dsn) as connection:
            snapshot_id, model = self._current(connection)
            if model != self._embedder.model:
                raise EmbeddingModelMismatch(
                    f"the schema was embedded with {model} and the question would be embedded with "
                    f"{self._embedder.model}; similarities between the two mean nothing"
                )
            scored = []
            for text, vector in zip(texts, vectors):
                rows = connection.execute(
                    _SCORE, {"vector": _literal(vector), "text": text, "snapshot": snapshot_id}
                ).fetchall()
                scored.append(tuple(RawScore(table, column, float(s), float(k)) for table, column, s, k in rows))
        return scored

    def score_question(self, question: str) -> ScoredQuestion:
        """The question and each of its terms, scored. One embedder call."""
        terms = make_terms(self.tokens(question))
        scored = self.score_many([question, *(term.text for term in terms)])
        return ScoredQuestion(question, scored[0], tuple(zip(terms, scored[1:])))

    def _current(self, connection) -> tuple[int, str]:
        row = connection.execute("select id, embedding_model from schema_snapshots where is_current").fetchone()
        if row is None:
            raise SchemaNotEmbedded("no schema snapshot is stored: run python -m app.ingest_schema")
        (unembedded,) = connection.execute(
            "select count(*) from schema_elements where snapshot_id = %s and embedding is null", (row[0],)
        ).fetchone()
        if unembedded or row[1] is None:
            raise SchemaNotEmbedded(
                f"{unembedded} elements of the current snapshot have no embedding: run python -m app.ingest_schema"
            )
        return row


def _literal(vector) -> str:
    """A vector as pgvector reads it from text: [0.1,0.2,...]."""
    return "[" + ",".join(repr(float(value)) for value in vector) + "]"
