"""The three schema tables: snapshots, elements, edges.

Revision ID: 0001
Revises:
Create Date: 2026-10-08

The first migration of the application store (DR-14, Design section 06,
DD-17). It creates only what step 6 needs. users, queries and traces arrive
at step 8, and queries carries user_id from the moment it exists (DR-08).

It is here, and not at step 8, because step 6 tunes its hybrid scoring
against Postgres full-text search itself. Tuning against a stand-in and
swapping the real thing in later would invalidate the tuning (T-04).

schema_snapshots   one row per ingestion. Added, never replaced (DD-17):
                   a new snapshot is marked current and the old one stays,
                   so a trace's schema_ref never points at nothing. At most
                   one row is current, and the database enforces it.

schema_elements    one row per table and one per column (DD-17: normalised
                   rows, because pgvector needs a real column). column_name
                   is null for a table's own row.
                     search_text  the text that is embedded and searched:
                                  the description of DD-08.
                     embedding    its vector; null until embedded (DR-11).
                     fts          the same text as a tsvector, generated by
                                  Postgres, so the keyword half of DD-09
                                  can never drift from the semantic half.
                   No vector index: at a few hundred rows a sequential
                   scan is exact, and an approximate index could change a
                   ranking between two runs. Departs from figure 4.

schema_edges       one row per COLUMN PAIR of a foreign key. A key of two
                   columns is two rows sharing key_number, ordered by
                   position. source, constraint_name and note belong to
                   the key and repeat on each of its rows.
"""

from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("create extension if not exists vector")

    op.execute(
        """
        create table schema_snapshots (
            id               bigint generated always as identity primary key,
            hash             text not null unique,
            source           text not null,
            is_current       boolean not null default false,
            embedding_model  text,
            created_at       timestamptz not null default now()
        )
        """
    )
    op.execute("create unique index schema_snapshots_one_current on schema_snapshots (is_current) where is_current")

    op.execute(
        """
        create table schema_elements (
            id                    bigint generated always as identity primary key,
            snapshot_id           bigint not null references schema_snapshots (id),
            table_name            text not null,
            column_name           text,
            position              integer not null,
            data_type             text,
            nullable              boolean,
            comment               text,
            primary_key_position  integer,
            readable              text not null,
            description           text not null,
            search_text           text not null,
            embedding             vector(1536),
            fts                   tsvector generated always as (to_tsvector('english', search_text)) stored,
            check ((column_name is null) = (data_type is null))
        )
        """
    )
    op.execute(
        "create unique index schema_elements_one_per_name "
        "on schema_elements (snapshot_id, table_name, coalesce(column_name, ''))"
    )
    op.execute("create index schema_elements_fts on schema_elements using gin (fts)")

    op.execute(
        """
        create table schema_edges (
            id               bigint generated always as identity primary key,
            snapshot_id      bigint not null references schema_snapshots (id),
            key_number       integer not null,
            position         integer not null,
            from_element_id  bigint not null references schema_elements (id),
            to_element_id    bigint not null references schema_elements (id),
            source           text not null check (source in ('catalog', 'overlay')),
            constraint_name  text,
            note             text,
            unique (snapshot_id, key_number, position)
        )
        """
    )


def downgrade() -> None:
    op.execute("drop table schema_edges")
    op.execute("drop table schema_elements")
    op.execute("drop table schema_snapshots")
